/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.form-group[_ngcontent-%COMP%] {\r\n  margin-right:20px;\r\n}\r\n.form-inline[_ngcontent-%COMP%] {\r\n  margin-bottom: 20px;\r\n}'];